# Generated by Django 4.1.2 on 2024-01-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('bed_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_occuipied', models.BooleanField(default=False)),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('medication', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
